"""
GitHub Issue Creator for Copilot Coding Agent.

Creates GitHub Issues for confirmed vulnerabilities, formatted so that
GitHub Copilot Coding Agent can automatically pick them up and generate
fix Pull Requests.

This implements the "Remediation Accelerator" pattern:
- Fixer Agent generates fix code (shown in dashboard)
- Issue Creator publishes to GitHub Issues
- Copilot Coding Agent picks up the issue and creates enhanced PR
"""

import os
import httpx

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO = os.getenv("GITHUB_REPO", "freddan58/devsecops-guardian")


async def create_security_issue(finding: dict, fix_suggestion: dict = None) -> dict:
    """Create a GitHub Issue for a confirmed vulnerability.

    The issue body is formatted for Copilot Coding Agent consumption,
    with structured vulnerability details and fix instructions.

    Args:
        finding: Confirmed vulnerability finding dict.
        fix_suggestion: Optional fix suggestion from the Fixer agent.

    Returns:
        Dict with issue_number, issue_url, and status.
    """
    severity_emoji = {
        "CRITICAL": "🔴",
        "HIGH": "🟠",
        "MEDIUM": "🟡",
        "LOW": "🟢",
    }

    emoji = severity_emoji.get(finding.get("severity", "MEDIUM"), "⚪")

    title = f"{emoji} [{finding.get('severity', 'MEDIUM')}] {finding.get('title', finding.get('vulnerability', 'Unknown'))} in {finding.get('file', 'unknown')}"

    fix_explanation = "No fix suggestion available."
    fix_code = "// Fix code will be generated by Copilot Agent"
    if fix_suggestion:
        fix_explanation = fix_suggestion.get("fix_explanation", fix_explanation)
        fix_code = fix_suggestion.get("fix_code", fix_code)

    body = f"""## Security Vulnerability Detected by DevSecOps Guardian

**Detected by**: SecurityScanner Agent (LLM-based analysis)
**Confirmed by**: VulnerabilityAnalyzer Agent (contextual reasoning)

### Details
| Field | Value |
|-------|-------|
| **Severity** | {finding.get('severity', 'N/A')} |
| **CWE** | {finding.get('cwe', 'N/A')} |
| **File** | `{finding.get('file', 'N/A')}` |
| **Line** | {finding.get('line', 'N/A')} |
| **Exploitability Score** | {finding.get('exploitability_score', 'N/A')}/100 |

### Description
{finding.get('description', 'No description available.')}

### Analyzer Reasoning
{finding.get('analysis_reasoning', 'No reasoning available.')}

### Suggested Fix
{fix_explanation}

```suggestion
{fix_code}
```

### Instructions for Copilot
Please fix the {finding.get('cwe', 'security')} vulnerability in `{finding.get('file', '')}` at line {finding.get('line', 'N/A')}.
Follow these security best practices:
1. Use parameterized queries for any SQL operations
2. Validate and sanitize all user inputs
3. Ensure proper authentication/authorization checks
4. Remove any hardcoded secrets (use environment variables)
5. Follow OWASP Secure Coding Guidelines
"""

    if not GITHUB_TOKEN:
        return {"status": "SKIPPED", "error": "GITHUB_TOKEN not set"}

    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"https://api.github.com/repos/{REPO}/issues",
            headers={
                "Authorization": f"Bearer {GITHUB_TOKEN}",
                "Accept": "application/vnd.github+json",
            },
            json={
                "title": title,
                "body": body,
                "labels": [
                    "security",
                    "vulnerability",
                    finding.get("severity", "medium").lower(),
                    "copilot-fix",
                ],
            },
        )

        if response.status_code == 201:
            issue_data = response.json()
            return {
                "issue_number": issue_data["number"],
                "issue_url": issue_data["html_url"],
                "status": "CREATED",
            }
        else:
            return {
                "status": "FAILED",
                "error": f"GitHub API error {response.status_code}: {response.text[:200]}",
            }


async def create_issues_for_scan(confirmed_findings: list, fixes: list = None) -> list:
    """Create GitHub Issues for all confirmed findings from a scan.

    Args:
        confirmed_findings: List of confirmed vulnerability findings.
        fixes: Optional list of fix suggestions from the Fixer agent.

    Returns:
        List of created issue references.
    """
    fixes_map = {}
    if fixes:
        for fix in fixes:
            fixes_map[fix.get("finding_id")] = fix

    results = []
    for finding in confirmed_findings:
        fix = fixes_map.get(finding.get("id"))
        result = await create_security_issue(finding, fix)
        results.append({
            "finding_id": finding.get("id"),
            "finding_title": finding.get("title", finding.get("vulnerability")),
            **result,
        })
        status_icon = "[OK]" if result["status"] == "CREATED" else "[SKIP]"
        print(f"  {status_icon} Issue for {finding.get('title', finding.get('vulnerability'))}: "
              f"{result.get('issue_url', result.get('error'))}")

    return results
